CREATE TABLE discounts (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "key" VARCHAR(8) NOT NULL UNIQUE,
  "uin" VARCHAR(8) NOT NULL UNIQUE,
  "is_hidden" BOOLEAN NOT NULL,
  "user_id" VARCHAR(8) NOT NULL,
  "store_name" VARCHAR(255) NOT NULL,
  "description" VARCHAR(255) NOT NULL
);


CREATE TABLE users (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "email" VARCHAR(255) NOT NULL UNIQUE,
  "user_id" VARCHAR(8) NOT NULL UNIQUE,
  "password_hash" VARCHAR(255) NOT NULL,
  "role" VARCHAR(255) NOT NULL,
  "enabled" BOOLEAN NOT NULL DEFAULT TRUE,
  "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
  "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL
);

CREATE TABLE pw_restore (
  "email" VARCHAR(255) NOT NULL UNIQUE,
  "hash" VARCHAR(255) NOT NULL UNIQUE
);


CREATE TABLE stores (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "user_id" VARCHAR(8) NOT NULL UNIQUE,
  "store_name" VARCHAR(255) NOT NULL UNIQUE,
  "store_image" VARCHAR(255) NOT NULL,
  "description" VARCHAR(4000),
  "discount_percent" INTEGER NOT NULL
);




