CREATE TABLE users (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "email" VARCHAR(255) NOT NULL UNIQUE,
  "password_hash" VARCHAR(255),
  "role" VARCHAR(255) NOT NULL,
  "enabled" BOOLEAN NOT NULL DEFAULT false,
  "account_hash" VARCHAR(255),
  "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
  "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL
);
